<?php
/**
 * Edit Outcome Content Partial
 * Content section for the edit outcome page
 */

// Include page header with configuration
require_once PROJECT_ROOT_PATH . 'app/views/layouts/page_header.php';
?>

<div class="outcomes-container">
    <!-- Error/Success messages -->
    <?php if (!empty($message)): ?>
        <div class="alert alert-<?= $message_type ?> alert-dismissible fade show outcomes-alert" role="alert">
            <i class="fas fa-<?= $message_type === 'danger' ? 'exclamation-triangle' : 'check-circle' ?> me-2"></i>
            <?= htmlspecialchars($message) ?>
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
    <?php endif; ?>

    <form method="POST" action="" class="outcome-edit-form">
        <!-- Outcome Information -->
        <div class="outcome-edit-header">
            <h2 class="outcome-edit-title"><?= htmlspecialchars($outcome['title']) ?></h2>
            <p class="outcome-edit-description">
                Edit the data for this outcome. Changes are saved automatically and you can preview the chart as you work.
            </p>
        </div>

        <!-- Data Entry Section -->
        <div class="form-section">
            <h3 class="form-section-title">
                <i class="fas fa-table me-2"></i>Data Entry
            </h3>
            
            <!-- Dynamic Table Container -->
            <div id="dynamic-table-container">
                <!-- Table will be generated by JavaScript -->
            </div>
            
            <!-- Chart Preview -->
            <div class="outcome-chart-container" style="display: none;">
                <div class="chart-header">
                    <div>
                        <h4 class="chart-title">Live Preview</h4>
                        <p class="chart-subtitle">Chart updates as you enter data</p>
                    </div>
                    <div class="chart-controls">
                        <div class="chart-type-selector">
                            <button type="button" class="chart-type-btn active" data-type="line">
                                <i class="fas fa-chart-line"></i> Line
                            </button>
                            <button type="button" class="chart-type-btn" data-type="bar">
                                <i class="fas fa-chart-bar"></i> Bar
                            </button>
                        </div>
                    </div>
                </div>
                
                <div class="chart-content">
                    <div class="chart-canvas-container">
                        <canvas id="metricChart" class="chart-canvas"></canvas>
                    </div>
                </div>
            </div>
        </div>

        <!-- Hidden inputs for structure data -->
        <input type="hidden" id="row_config" name="row_config" value="<?= htmlspecialchars(json_encode($rows)) ?>">
        <input type="hidden" id="column_config" name="column_config" value="<?= htmlspecialchars(json_encode($columns)) ?>">

        <!-- Form Actions -->
        <div class="form-actions">
            <div class="form-actions-left">
                <button type="submit" class="btn btn-primary" id="save-outcome">
                    <i class="fas fa-save"></i> Save Changes
                </button>
                <button type="button" class="btn btn-outline-secondary" id="preview-chart">
                    <i class="fas fa-chart-line"></i> Preview Chart
                </button>
            </div>
            <div class="form-actions-right">
                <a href="view_outcome.php?id=<?= $outcome_id ?>" class="btn btn-outline-primary">
                    <i class="fas fa-eye"></i> View Details
                </a>
                <a href="submit_outcomes.php" class="btn btn-outline-secondary">
                    <i class="fas fa-arrow-left"></i> Back to List
                </a>
            </div>
        </div>
    </form>
</div>

<!-- JavaScript configuration -->
<script>
    // Pass configuration data to JavaScript
    window.outcomeId = <?= json_encode($outcome_id) ?>;
    window.outcomeData = <?= json_encode($outcome) ?>;
    window.initialRowConfig = <?= json_encode($rows) ?>;
    window.initialColumnConfig = <?= json_encode($columns) ?>;
</script>
