<?php
// Centralized config: table names, column names, and schema for all tables

return [
    'tables' => [
        'agency' => 'agency',
        'audit_logs' => 'audit_logs',
        'initiatives' => 'initiatives',
        'notifications' => 'notifications',
        'outcomes_details' => 'outcomes_details',
        'programs' => 'programs',
        'program_attachments' => 'program_attachments',
        'program_outcome_links' => 'program_outcome_links',
        'program_submissions' => 'program_submissions',
        'reporting_periods' => 'reporting_periods',
        'reports' => 'reports',
        'targets' => 'targets',
        'users' => 'users',
    ],
    'columns' => [
        'agency' => [
            'id' => 'agency_id',
            'name' => 'agency_name',
            'created_at' => 'created_at',
            'updated_at' => 'updated_at',
        ],
        'audit_logs' => [
            'id' => 'id',
            'user_id' => 'user_id',
            'action' => 'action',
            'details' => 'details',
            'ip_address' => 'ip_address',
            'status' => 'status',
            'created_at' => 'created_at',
        ],
        'initiatives' => [
            'id' => 'initiative_id',
            'name' => 'initiative_name',
            'number' => 'initiative_number',
            'description' => 'initiative_description',
            'start_date' => 'start_date',
            'end_date' => 'end_date',
            'is_active' => 'is_active',
            'created_by' => 'created_by',
            'created_at' => 'created_at',
            'updated_at' => 'updated_at',
        ],
        'notifications' => [
            'id' => 'notification_id',
            'user_id' => 'user_id',
            'message' => 'message',
            'type' => 'type',
            'read_status' => 'read_status',
            'created_at' => 'created_at',
            'action_url' => 'action_url',
        ],
        'outcomes_details' => [
            'id' => 'detail_id',
            'name' => 'detail_name',
            'display_config' => 'display_config',
            'detail_json' => 'detail_json',
            'is_cumulative' => 'is_cumulative',
            'created_at' => 'created_at',
            'updated_at' => 'updated_at',
            'is_important' => 'is_important',
            'indicator_type' => 'indicator_type',
            'agency_id' => 'agency_id',
        ],
        'programs' => [
            'id' => 'program_id',
            'name' => 'program_name',
            'number' => 'program_number',
            'initiative_id' => 'initiative_id',
            'agency_id' => 'agency_id',
            'users_assigned' => 'users_assigned',
            'created_at' => 'created_at',
            'updated_at' => 'updated_at',
            'created_by' => 'created_by',
            'attachment_count' => 'attachment_count',
            'status' => 'status',
            'hold_point' => 'hold_point',
            'targets_linked' => 'targets_linked',
        ],
        'program_attachments' => [
            'id' => 'attachment_id',
            'program_id' => 'program_id',
            'file_name' => 'file_name',
            'file_path' => 'file_path',
            'file_size' => 'file_size',
            'file_type' => 'file_type',
            'uploaded_by' => 'uploaded_by',
            'uploaded_at' => 'uploaded_at',
            'is_active' => 'is_active',
        ],
        'program_outcome_links' => [
            'id' => 'link_id',
            'program_id' => 'program_id',
            'outcome_id' => 'outcome_id',
            'created_by' => 'created_by',
            'created_at' => 'created_at',
        ],
        'program_submissions' => [
            'id' => 'submission_id',
            'program_id' => 'program_id',
            'period_id' => 'period_id',
            'submitted_by' => 'submitted_by',
            'content_json' => 'content_json',
            'submission_date' => 'submission_date',
            'updated_at' => 'updated_at',
            'is_draft' => 'is_draft',
        ],
        'reporting_periods' => [
            'id' => 'period_id',
            'year' => 'year',
            'period_type' => 'period_type',
            'period_number' => 'period_number',
            'start_date' => 'start_date',
            'end_date' => 'end_date',
            'status' => 'status',
            'updated_at' => 'updated_at',
            'created_at' => 'created_at',
        ],
        'reports' => [
            'id' => 'report_id',
            'period_id' => 'period_id',
            'report_name' => 'report_name',
            'description' => 'description',
            'pdf_path' => 'pdf_path',
            'pptx_path' => 'pptx_path',
            'generated_by' => 'generated_by',
            'generated_at' => 'generated_at',
            'is_public' => 'is_public',
        ],
        'targets' => [
            'id' => 'target_id',
            'target_name' => 'target_name',
            'status_description' => 'status_description',
            'created_at' => 'created_at',
            'updated_at' => 'updated_at',
        ],
        'users' => [
            'id' => 'user_id',
            'username' => 'username',
            'pw' => 'pw',
            'fullname' => 'fullname',
            'email' => 'email',
            'agency_id' => 'agency_id',
            'role' => 'role',
            'created_at' => 'created_at',
            'updated_at' => 'updated_at',
            'is_active' => 'is_active',
        ],
    ],
    'schema' => include __DIR__ . '/database_schema.php',
]; 