<?php
/**
 * Public Reports - Agency View
 * 
 * Interface for agency users to view and download public reports 
 * that have been made available by admin users.
 */

// Define project root path for consistent file references
if (!defined('PROJECT_ROOT_PATH')) {
    define('PROJECT_ROOT_PATH', rtrim(dirname(dirname(dirname(dirname(__DIR__)))), DIRECTORY_SEPARATOR) . DIRECTORY_SEPARATOR);
}

// Include necessary files
require_once PROJECT_ROOT_PATH . 'app/config/config.php';
require_once PROJECT_ROOT_PATH . 'app/lib/db_connect.php';
require_once PROJECT_ROOT_PATH . 'app/lib/session.php';
require_once PROJECT_ROOT_PATH . 'app/lib/functions.php';
require_once PROJECT_ROOT_PATH . 'app/lib/agencies/index.php';

// Verify user is an agency
if (!is_agency()) {
    header('Location: ' . APP_URL . '/login.php');
    exit;
}

// Set page title
$pageTitle = 'Public Reports';

// Get public reports
$public_reports = get_public_reports();

// Include header
require_once PROJECT_ROOT_PATH . 'app/views/layouts/header.php';

// Configure modern page header
$header_config = [
    'title' => 'Public Reports',
    'subtitle' => 'Download reports made available by administrators',
    'variant' => 'blue',
    'actions' => []
];

// Include modern page header
require_once PROJECT_ROOT_PATH . 'app/views/layouts/page_header.php';
?>

<!-- Public Reports List -->
<?php if (empty($public_reports)): ?>
    <div class="alert alert-info">
        <i class="fas fa-info-circle me-2"></i>
        No public reports are currently available for download.
    </div>
<?php else: ?>
    <div class="card shadow-sm mb-4">
        <div class="card-header d-flex justify-content-between align-items-center">
            <h5 class="card-title m-0">Available Public Reports</h5>
            <span class="badge bg-primary"><?php echo count($public_reports); ?> Reports</span>
        </div>
        <div class="card-body">
            <div class="table-responsive">
                <table class="table table-hover table-custom">
                    <thead>
                        <tr>
                            <th>Report Name</th>
                            <th>Description</th>
                            <th>Type</th>
                            <th>Generated</th>
                            <th>Actions</th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php foreach ($public_reports as $report): ?>
                            <tr>
                                <td>
                                    <div class="fw-medium"><?php echo htmlspecialchars($report['report_name']); ?></div>
                                </td>
                                <td><?php echo htmlspecialchars($report['description'] ?? 'No description available'); ?></td>                                <td>
                                    <span class="badge bg-<?php echo $report['report_type'] === 'pptx' ? 'primary' : 'info'; ?>">
                                        <?php echo strtoupper(htmlspecialchars($report['report_type'])); ?>
                                    </span>
                                </td>
                                <td><?php echo date('M j, Y g:i A', strtotime($report['generated_at'])); ?></td>                                <td>
                                    <div class="btn-group btn-group-sm">
                                        <a href="<?php echo APP_URL; ?>/download.php?type=report&file=<?php echo urlencode($report['file_path']); ?>" 
                                           class="btn btn-outline-success" 
                                           title="Download Report">
                                            <i class="fas fa-download me-1"></i> Download
                                        </a>
                                    </div>
                                </td>
                            </tr>
                        <?php endforeach; ?>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
<?php endif; ?>

<!-- Info Card -->
<div class="card shadow-sm">
    <div class="card-header">
        <h5 class="card-title m-0">About Public Reports</h5>
    </div>
    <div class="card-body">
        <div class="row">
            <div class="col-md-12">
                <div class="d-flex">
                    <div class="flex-shrink-0">
                        <span class="badge bg-info p-2"><i class="fas fa-info-circle"></i></span>
                    </div>
                    <div class="flex-grow-1 ms-3">
                        <h6 class="mt-0">What are Public Reports?</h6>
                        <p class="mb-0">
                            Public reports are reports generated by administrators that have been made available 
                            to all agencies for download. These reports may contain sector-wide insights, 
                            comparative analysis, or other information relevant to all agencies.
                        </p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<?php
// Include footer
require_once PROJECT_ROOT_PATH . 'app/views/layouts/footer.php';
?>
